# configuracion de la aplicacion
server:
  port: 8091

# para ver la consola H2 en el browser
# http://localhost:8091/h2-console
# Habilitar consola de H2

spring:
  h2:
    console:
      enabled: true
# ==============================
# DB: customizable de acuerdo a la base de datos que se utiliza. En este caso H2
# ==============================
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

# ==============================
# JPA / HIBERNATE
# ==============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
